### ISSUE TITLE
bug(toolbox): problème création release branche develop

### ISSUE THREAD

**Issue by BesnierJulien** [GitHarpon/git-harpon#133]
Lors d'une tentative de création d'une release sur la branche develop, nous obtenons l'erreur suivante : 

ERROR in src/app/screens/toolbox/toolbox.component.html(667,75): : Property ‘first’ does not exist on type ‘ToolboxComponent’.
src/app/screens/toolbox/toolbox.component.html(667,75): : Property ‘text’ does not exist on type ‘ToolboxComponent’.
src/app/screens/toolbox/toolbox.component.html(667,75): : Property ‘area’ does not exist on type ‘ToolboxComponent’.
src/app/screens/toolbox/toolbox.component.html(678,75): : Property ‘first’ does not exist on type ‘ToolboxComponent’.
src/app/screens/toolbox/toolbox.component.html(678,75): : Property ‘text’ does not exist on type ‘ToolboxComponent’.
src/app/screens/toolbox/toolbox.component.html(678,75): : Property ‘area’ does not exist on type ‘ToolboxComponent’.
src/app/components/commit-text-area/commit-text-area.component.html(4,75): : Property ‘name’ does not exist on type ‘CommitTextAreaComponent’.

**Comment by JulienLamy76** [comment]
Corrigé via #145
