### ISSUE TITLE
bug(open-terminal): Sur windows git bash et powershell ne s'ouvre pas correctement

### ISSUE THREAD

**Issue by Nemtecl** [GitHarpon/git-harpon#173]
Sur Windows, git bash et PowerShell ne s'ouvre pas correctement.
PowerShell s'ouvre mais reste en attente et git bash se ferme directement. Le problème vient probablement de la commande utilisée pour changer le chemin à l'ouverture.

**Comment by BesnierJulien** [comment]
Corrigé via #190
