### ISSUE TITLE
Please provide binaries for download

### ISSUE THREAD

**Issue by probonopd** [GitHarpon/git-harpon#33]
Please provide binaries for download, thank you. I am especially looking for an AppImage for Linux.

**Comment by Nemtecl** [comment]
You can create an AppImage for Linux by runing `yarn electron:linux`

**Comment by probonopd** [comment]
Thanks @Nemtecl I know that but in order to include your application in the AppImageHub central directory of downloadable AppImages we'd need to have a download URL. Thanks for your consideration.

**Comment by Nemtecl** [comment]
I understand your request. Nevertheless this is not possible for several reasons:
1) The application is not developed at all, so it is not necessary to include it on the AppImageHub central directory
2) It is available on macOS, Windows and Linux. Builds are created in the same "release" folder. Push the release on GitHub will therefore pose a problem for collaborators working on macOS/Windows.

I close (for now) the issue. Once the application is more elaborate, we will come back to you to find a viable solution.

The features will arrive between February and the end of April. I'll get back to you by then!

**Comment by Nemtecl** [comment]
@probonopd  you can find binaries for linux in a .zip here : https://github.com/GitHarpon/git-harpon/releases

**Comment by probonopd** [comment]
Thanks for getting back to me once you think the application is ready for AppImageHub. 👍
